# Build Parkour Recorder mod for Minecraft 1.12.2. Alert if build fails.

name: Java CI with Gradle

on:
  push:
    branches: [ master-1.12.2 ]
  pull_request:
    branches: [ master-1.12.2 ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'jdk'
    - run: ./gradlew build
